### ISSUE TITLE
Implement session timeouts

### ISSUE THREAD

**Issue by HaydernMcLendern** [ConnorLambert/ProgressTracker#27]
Add a new column to User table that updates every time a user loads a page. When loading any new page, check to see if a set amount of time (like thirty minutes) has elapsed since then and log the user out if it exceeds the timeout limit.

**Comment by uninformed** [comment]
As stated in https://github.com/ConnorLambert/ProgressTracker/issues/34#issuecomment-439654976, this has been done without using the DB for greater efficiency.
