### ISSUE TITLE
Create login template

### ISSUE THREAD

**Issue by uninformed** [ConnorLambert/ProgressTracker#8]
Just needs a username/password login form.

**Comment by ConnorLambert** [comment]
[capstoneProjPages.zip](https://github.com/ConnorLambert/ProgressTracker/files/2430746/capstoneProjPages.zip)

Please check for correctness. Just a base skeleton of the login form with no styling added.  Will not work correctly unless put into a Flask application.

**Comment by ConnorLambert** [comment]
Also sorry for the obnoxious ZIP, not allowed to post actual html files in here.

**Comment by uninformed** [comment]
Template included in ae4c4dfa.
